# Generated by Django 4.2.11 on 2025-10-31 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("trader", "0033_remove_bidding_items_needed_itemneeded_bidding_and_more"),
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="job",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_messages",
                to="trader.jobs",
            ),
        ),
    ]
