# Generated by Django 4.2.11 on 2025-07-18 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [

    ]

    operations = [
        migrations.CreateModel(
            name="TraderRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=50)),
                ("password", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "company_type",
                    models.CharField(
                        choices=[
                            ("sole_trader", "Sole Trader"),
                            ("company", "Company"),
                        ],
                        default="company",
                        max_length=100,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "company_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "company_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "company_landline",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("gst_registered", models.BooleanField(default=False)),
                ("abn", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "industry",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("air_conditioning", "Air Conditioning"),
                            ("cleaning", "Cleaning"),
                            ("electrical", "Electrical"),
                            ("gardening", "Gardening"),
                            ("general_merchandise", "General Merchandise"),
                            ("glazing", "Glazing"),
                            ("pest_control", "Pest Control"),
                            ("plumbing-gas", "Plumbing / Gas"),
                            ("tree_cutting", "Tree Cutting"),
                            ("steel_works", "Steel Works"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "other_expertise",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("air_conditioning", "Air Conditioning"),
                            ("cleaning", "Cleaning"),
                            ("electrical", "Electrical"),
                            ("gardening", "Gardening"),
                            ("general_merchandise", "General Merchandise"),
                            ("glazing", "Glazing"),
                            ("pest_control", "Pest Control"),
                            ("plumbing-gas", "Plumbing / Gas"),
                            ("tree_cutting", "Tree Cutting"),
                            ("steel_works", "Steel Works"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("state", models.CharField(blank=True, max_length=100)),
                ("municipality", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                (
                    "address_line_1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_line_2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("teamName", models.CharField(max_length=255)),
                ("position", models.CharField(max_length=100)),
                (
                    "labour_rate_per_hour",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "callout_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("contact_number", models.CharField(blank=True, max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("active_postal_codes", models.CharField(blank=True, max_length=255)),
                ("holidays", models.TextField(blank=True)),
                ("time_in", models.TimeField(blank=True, null=True)),
                ("time_out", models.TimeField(blank=True, null=True)),
                ("IsWorkInHoliday", models.BooleanField(default=False)),
                ("holidayTime_in", models.TimeField(blank=True, null=True)),
                ("holidayTime_out", models.TimeField(blank=True, null=True)),
                (
                    "trader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_members",
                        to="trader.traderregistration",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Jobs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("priority", models.BooleanField(default=False)),
                ("job_code", models.CharField(max_length=20, unique=True)),
                ("notes", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("quoted", "Quoted"),
                            ("confirmed", "Confirmed"),
                            ("approved", "Approved"),
                            ("scheduled", "Scheduled"),
                        ],
                        default="quoted",
                        max_length=20,
                    ),
                ),
                ("quoted_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs_agent",
                        to="agent.agentregister",
                    ),
                ),
                (
                    "renter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs_renter",
                        to="renter.renter",
                    ),
                ),
                (
                    "trader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs_trader",
                        to="trader.traderregistration",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContractorLicense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contractorLicense", models.CharField(max_length=255)),
                (
                    "trader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contractor_license",
                        to="trader.traderregistration",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bidding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "labour_per_hour",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "callout_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("parts_qty", models.PositiveIntegerField(default=0)),
                (
                    "parts_unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "appliance_model_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "appliance_model",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_approved",
                    models.BooleanField(
                        blank=True,
                        default=None,
                        help_text="None=pending, True=approved, False=rejected",
                        null=True,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("approval_notes", models.TextField(blank=True, null=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bid_agent",
                        to="agent.agentregister",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_bids",
                        to="agent.agentregister",
                    ),
                ),
                (
                    "jobs",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs_related",
                        to="trader.jobs",
                    ),
                ),
                (
                    "team_member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="teams_related",
                        to="trader.teammember",
                    ),
                ),
                (
                    "trader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bid_trader",
                        to="trader.traderregistration",
                    ),
                ),
            ],
        ),
    ]
