# Generated by Django 5.2.1 on 2025-06-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TraderRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('company_type', models.CharField(max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('company_address', models.CharField(blank=True, max_length=255)),
                ('company_email', models.EmailField(blank=True, max_length=254)),
                ('company_landline', models.CharField(blank=True, max_length=50)),
                ('contractor_license', models.CharField(blank=True, max_length=100)),
                ('gst_registered', models.BooleanField(default=False)),
                ('abn', models.CharField(blank=True, max_length=20)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('other_expertise', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
