# Generated by Django 5.2.3 on 2025-07-20 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='holidays',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
