# Generated by Django 5.2.1 on 2025-06-07 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='traderregistration',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='traderregistration',
            name='company_type',
            field=models.CharField(choices=[('sole_trader', 'Sole Trader'), ('company', 'Company'), ('partnership', 'Partnership')], default='sole_trader', max_length=100),
        ),
        migrations.AlterField(
            model_name='traderregistration',
            name='industry',
            field=models.CharField(blank=True, choices=[('air_conditioning', 'Air Conditioning'), ('cleaning', 'Cleaning'), ('electrical', 'Electrical'), ('gardening', 'Gardening'), ('general_merchandise', 'General Merchandise'), ('glazing', 'Glazing'), ('pest_control', 'Pest Control'), ('plumbing-gas', 'Plumbing / Gas'), ('tree_cutting', 'Tree Cutting'), ('steel_works', 'Steel Works')], max_length=100),
        ),
        migrations.AlterField(
            model_name='traderregistration',
            name='other_expertise',
            field=models.CharField(blank=True, choices=[('air_conditioning', 'Air Conditioning'), ('cleaning', 'Cleaning'), ('electrical', 'Electrical'), ('gardening', 'Gardening'), ('general_merchandise', 'General Merchandise'), ('glazing', 'Glazing'), ('pest_control', 'Pest Control'), ('plumbing-gas', 'Plumbing / Gas'), ('tree_cutting', 'Tree Cutting'), ('steel_works', 'Steel Works')], max_length=100),
        ),
    ]
