# Generated by Django 5.2.1 on 2025-06-08 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0002_traderregistration_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderregistration',
            name='confirm_password',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
