# Generated by Django 5.2.1 on 2025-07-22 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_initial'),
        ('trader', '0002_alter_teammember_holidays'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_property', to='agent.property'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='renter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
