# Generated by Django 5.2.1 on 2025-07-22 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0003_jobs_property_alter_jobs_renter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('isurgent', models.BooleanField(default=False, help_text='Is this service urgent?')),
                ('locationName', models.CharField(blank=True, max_length=100, null=True)),
                ('marketName', models.CharField(blank=True, max_length=100, null=True)),
                ('secondaryMarketName', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this service currently active?')),
            ],
        ),
        migrations.AlterField(
            model_name='traderregistration',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='industry_services', to='trader.services'),
        ),
        migrations.AlterField(
            model_name='traderregistration',
            name='other_expertise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_expertise_services', to='trader.services'),
        ),
    ]
