# Generated by Django 5.2.1 on 2025-06-08 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0003_traderregistration_confirm_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traderregistration',
            name='confirm_password',
        ),
        migrations.AlterField(
            model_name='traderregistration',
            name='company_type',
            field=models.CharField(choices=[('sole_trader', 'Sole Trader'), ('company', 'Company')], default='sole_trader', max_length=100),
        ),
    ]
