# Generated by Django 5.2.1 on 2025-06-09 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0004_remove_traderregistration_confirm_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=100)),
                ('labour_rate_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('callout_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('active_postal_codes', models.CharField(blank=True, max_length=255)),
                ('holidays', models.TextField(blank=True)),
                ('time_in', models.TimeField(blank=True, null=True)),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='trader.traderregistration')),
            ],
        ),
    ]
