# Generated by Django 5.2.1 on 2025-07-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0005_jobs_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderregistration',
            name='industry',
            field=models.CharField(blank=True, choices=[('air_conditioning', 'Air Conditioning'), ('cleaning', 'Cleaning'), ('electrical', 'Electrical'), ('gardening', 'Gardening'), ('general_merchandise', 'General Merchandise'), ('glazing', 'Glazing'), ('pest_control', 'Pest Control'), ('plumbing-gas', 'Plumbing / Gas'), ('tree_cutting', 'Tree Cutting'), ('steel_works', 'Steel Works')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='traderregistration',
            name='other_expertise',
            field=models.CharField(blank=True, choices=[('air_conditioning', 'Air Conditioning'), ('cleaning', 'Cleaning'), ('electrical', 'Electrical'), ('gardening', 'Gardening'), ('general_merchandise', 'General Merchandise'), ('glazing', 'Glazing'), ('pest_control', 'Pest Control'), ('plumbing-gas', 'Plumbing / Gas'), ('tree_cutting', 'Tree Cutting'), ('steel_works', 'Steel Works')], max_length=100, null=True),
        ),
    ]
