# Generated by Django 5.2.1 on 2025-06-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0005_teammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderregistration',
            name='password',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
