# Generated by Django 5.2.1 on 2025-06-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0006_alter_traderregistration_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderregistration',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
