# Generated by Django 5.2.1 on 2025-07-22 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0006_alter_traderregistration_industry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
