# Generated by Django 5.2.1 on 2025-06-13 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0007_alter_traderregistration_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='IsWorkInHoliday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teammember',
            name='holidayTime_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='holidayTime_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='traderregistration',
            name='abn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='traderregistration',
            name='company_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='traderregistration',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='traderregistration',
            name='company_landline',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='traderregistration',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='traderregistration',
            name='company_type',
            field=models.CharField(choices=[('sole_trader', 'Sole Trader'), ('company', 'Company')], default='company', max_length=100),
        ),
        migrations.AlterField(
            model_name='traderregistration',
            name='industry',
            field=models.CharField(blank=True, choices=[('air_conditioning', 'Air Conditioning'), ('cleaning', 'Cleaning'), ('electrical', 'Electrical'), ('gardening', 'Gardening'), ('general_merchandise', 'General Merchandise'), ('glazing', 'Glazing'), ('pest_control', 'Pest Control'), ('plumbing-gas', 'Plumbing / Gas'), ('tree_cutting', 'Tree Cutting'), ('steel_works', 'Steel Works')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='traderregistration',
            name='other_expertise',
            field=models.CharField(blank=True, choices=[('air_conditioning', 'Air Conditioning'), ('cleaning', 'Cleaning'), ('electrical', 'Electrical'), ('gardening', 'Gardening'), ('general_merchandise', 'General Merchandise'), ('glazing', 'Glazing'), ('pest_control', 'Pest Control'), ('plumbing-gas', 'Plumbing / Gas'), ('tree_cutting', 'Tree Cutting'), ('steel_works', 'Steel Works')], max_length=100, null=True),
        ),
    ]
