# Generated by Django 5.2.1 on 2025-07-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0007_alter_services_created_at_alter_services_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
