# Generated by Django 5.2.1 on 2025-08-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0008_jobs_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
