# Generated by Django 5.2.1 on 2025-06-13 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0008_teammember_isworkinholiday_teammember_holidaytime_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderregistration',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='traderregistration',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='traderregistration',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='traderregistration',
            name='municipality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='traderregistration',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='traderregistration',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
