# Generated by Django 5.2.3 on 2025-08-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0009_jobs_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
