# Generated by Django 5.2.3 on 2025-06-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0009_traderregistration_address_line_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderregistration',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
