# Generated by Django 5.2.3 on 2025-08-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0010_bidding_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='approved_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
