# Generated by Django 5.2.1 on 2025-06-28 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0010_alter_traderregistration_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='name',
            new_name='teamName',
        ),
    ]
