# Generated by Django 5.2.1 on 2025-08-11 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0011_alter_bidding_approved_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traderregistration',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='traderregistration',
            name='other_expertise',
        ),
    ]
