# Generated by Django 5.2.1 on 2025-06-28 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0011_rename_name_teammember_teamname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='IsWorkInHoliday',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='active_postal_codes',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='callout_rate',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='email',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='holidayTime_in',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='holidayTime_out',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='holidays',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='labour_rate_per_hour',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='time_in',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='time_out',
        ),
    ]
