# Generated by Django 5.2.1 on 2025-06-28 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0012_remove_teammember_isworkinholiday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traderregistration',
            name='contractor_license',
        ),
        migrations.CreateModel(
            name='ContractorLicence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=100)),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_license', to='trader.traderregistration')),
            ],
        ),
    ]
