# Generated by Django 5.2.1 on 2025-08-11 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0012_remove_traderregistration_industry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraderIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(choices=[('air_conditioning', 'Air Conditioning'), ('cleaning', 'Cleaning'), ('electrical', 'Electrical'), ('gardening', 'Gardening'), ('general_merchandise', 'General Merchandise'), ('glazing', 'Glazing'), ('pest_control', 'Pest Control'), ('plumbing-gas', 'Plumbing / Gas'), ('tree_cutting', 'Tree Cutting'), ('steel_works', 'Steel Works')], max_length=100)),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industries', to='trader.traderregistration')),
            ],
        ),
    ]
