# Generated by Django 5.2.1 on 2025-06-28 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0013_remove_traderregistration_contractor_license_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='IsWorkInHoliday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teammember',
            name='active_postal_codes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='teammember',
            name='callout_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='contact_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='teammember',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='teammember',
            name='holidayTime_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='holidayTime_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='holidays',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='labour_rate_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='time_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='time_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
