# Generated by Django 5.2.3 on 2025-09-16 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0015_jobs_issue_been_fixed_before_jobs_issue_found_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraderNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_references', models.CharField(blank=True, max_length=255, null=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('job_alerts', models.BooleanField(default=True)),
                ('feedback_requests', models.BooleanField(default=True)),
                ('message_description', models.TextField(blank=True, null=True)),
                ('seen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trader_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trader.traderregistration')),
            ],
        ),
    ]
