# Generated by Django 5.2.1 on 2025-07-02 00:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_alter_property_agent'),
        ('renter', '0009_alter_property_agent_alter_property_renter'),
        ('trader', '0015_contractorlicense_delete_contractorlicence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_code', models.CharField(max_length=20, unique=True)),
                ('notes', models.TextField()),
                ('status', models.CharField(choices=[('quoted', 'Quoted'), ('confirmed', 'Confirmed'), ('approved', 'Approved'), ('scheduled', 'Scheduled')], default='quoted', max_length=20)),
                ('quoted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_agent', to='agent.agentregister')),
                ('renter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_renter', to='renter.renter')),
                ('trader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_trader', to='trader.traderregistration')),
            ],
        ),
    ]
