# Generated by Django 5.2.1 on 2025-07-02 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0016_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='priority',
            field=models.BooleanField(default=False),
        ),
    ]
