# Generated by Django 5.2.3 on 2025-09-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0016_tradernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradernotification',
            name='priority',
            field=models.BooleanField(default=False),
        ),
    ]
