# Generated by Django 5.2.3 on 2025-09-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0017_tradernotification_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradernotification',
            name='feedback_requests',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tradernotification',
            name='job_alerts',
            field=models.BooleanField(default=False),
        ),
    ]
