# Generated by Django 5.2.1 on 2025-07-04 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_alter_property_agent'),
        ('trader', '0018_bidding'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='approval_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bidding',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bidding',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_bids', to='agent.agentregister'),
        ),
        migrations.AddField(
            model_name='bidding',
            name='is_approved',
            field=models.BooleanField(blank=True, default=None, help_text='None=pending, True=approved, False=rejected', null=True),
        ),
    ]
