# Generated by Django 5.2.3 on 2025-09-16 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0018_alter_tradernotification_feedback_requests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradernotification',
            name='trader_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trader_notifs', to='trader.traderregistration'),
        ),
    ]
