# Generated by Django 5.2.1 on 2025-09-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0019_alter_tradernotification_trader_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradernotification',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
