# Generated by Django 5.2.1 on 2025-10-01 15:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0020_tradernotification_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='approved_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='confirmed_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='issue_found_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='quoted_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='renter_availability',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='scheduled_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
