# Generated by Django 5.2.1 on 2025-10-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0021_alter_jobs_approved_at_alter_jobs_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
