# Generated by Django 5.2.1 on 2025-10-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0022_jobs_end_date_jobs_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bidding',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
