# Generated by Django 5.2.3 on 2025-10-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0023_bidding_end_date_bidding_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderregistration',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='traderregistration',
            name='isDirector',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='traderregistration',
            name='isTeamMember',
            field=models.BooleanField(default=False),
        ),
    ]
