# Generated by Django 5.2.3 on 2025-10-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0025_teammember_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderregistration',
            name='isDirector',
            field=models.BooleanField(default=True),
        ),
    ]
