# Generated by Django 5.2.3 on 2025-10-06 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0009_agentregister_is_admin_and_more'),
        ('trader', '0026_alter_traderregistration_isdirector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_number', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('is_approved', models.BooleanField(blank=True, default=None, help_text='None=pending, True=approved, False=rejected', null=True)),
                ('approved_at', models.DateField(auto_now_add=True, null=True)),
                ('approval_notes', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_approve_by', to='agent.agentregister')),
                ('team_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_teams_related', to='trader.teammember')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_trader', to='trader.traderregistration')),
            ],
        ),
    ]
