# Generated by Django 5.2.3 on 2025-10-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0027_leaves'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaves',
            name='leave_type',
            field=models.CharField(blank=True, choices=[('vacation', 'Vacation Leave'), ('sick', 'Sick Leave')], max_length=100, null=True),
        ),
    ]
