# Generated by Django 5.2.3 on 2025-10-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0028_leaves_leave_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaves',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
