# Generated by Django 5.2.3 on 2025-10-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0029_leaves_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='bid_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobs',
            name='bid_status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20),
        ),
    ]
