# Generated by Django 5.2.3 on 2025-10-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0030_jobs_bid_count_jobs_bid_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidding',
            name='team_member',
        ),
        migrations.AlterField(
            model_name='traderindustry',
            name='industry',
            field=models.CharField(choices=[('air_conditioning', 'Air Conditioning'), ('cleaning', 'Cleaning'), ('electrical', 'Electrical'), ('gardening', 'Gardening'), ('general_maintenance', 'General Maintenance'), ('glazing', 'Glazing'), ('pest_control', 'Pest Control'), ('plumbing_gas', 'Plumbing / Gas'), ('tree_cutting', 'Tree Cutting'), ('steel_works', 'Steel Works'), ('safety', 'Safety')], max_length=100),
        ),
        migrations.AlterField(
            model_name='traderregistration',
            name='industry',
            field=models.CharField(blank=True, choices=[('air_conditioning', 'Air Conditioning'), ('cleaning', 'Cleaning'), ('electrical', 'Electrical'), ('gardening', 'Gardening'), ('general_maintenance', 'General Maintenance'), ('glazing', 'Glazing'), ('pest_control', 'Pest Control'), ('plumbing_gas', 'Plumbing / Gas'), ('tree_cutting', 'Tree Cutting'), ('steel_works', 'Steel Works'), ('safety', 'Safety')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bidding',
            name='team_member',
            field=models.ManyToManyField(blank=True, related_name='biddings_related', to='trader.teammember'),
        ),
    ]
