# Generated by Django 5.2.3 on 2025-10-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0031_remove_bidding_team_member_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemNeeded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='bidding',
            name='items_needed',
            field=models.ManyToManyField(blank=True, related_name='items_related', to='trader.itemneeded'),
        ),
    ]
