# Generated by Django 5.2.3 on 2025-10-14 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0032_itemneeded_bidding_items_needed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidding',
            name='items_needed',
        ),
        migrations.AddField(
            model_name='itemneeded',
            name='bidding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_needed', to='trader.bidding'),
        ),
        migrations.AddField(
            model_name='itemneeded',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='itemneeded',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
