# Generated by Django 4.2.11 on 2025-11-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trader", "0033_remove_bidding_items_needed_itemneeded_bidding_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobs",
            name="issue_been_fixed_by_fmh_before",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="jobs",
            name="renter_availability_schedule",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
