# Generated by Django 5.2.3 on 2025-11-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0033_remove_bidding_items_needed_itemneeded_bidding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
