# Generated by Django 5.2.3 on 2025-11-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0034_bidding_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
