# Generated by Django 5.2.3 on 2025-11-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0035_alter_bidding_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='quote_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
