# Generated by Django 5.2.3 on 2025-11-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0036_bidding_quote_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
