# Generated by Django 4.2.11 on 2025-11-04 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trader", "0034_jobs_issue_been_fixed_by_fmh_before_and_more"),
        ("trader", "0037_alter_bidding_code"),
    ]

    operations = []
