# Generated by Django 4.2.11 on 2025-11-04 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trader", "0038_merge_20251104_1641"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobs",
            name="renter_issue_date",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
