# Generated by Django 4.2.11 on 2025-11-06 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trader", "0038_merge_20251105_1652"),
        ("trader", "0039_jobs_renter_issue_date"),
    ]

    operations = []
