# Generated by Django 5.2.1 on 2025-06-13 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('contact_person', models.CharField(max_length=50)),
                ('agency_id', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=50)),
                ('notes', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_address', models.CharField(blank=True, max_length=255, null=True)),
                ('company_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('company_landline', models.CharField(blank=True, max_length=50, null=True)),
                ('contractor_license', models.CharField(blank=True, max_length=100)),
                ('service', models.CharField(blank=True, choices=[('air_conditioning', 'Air Conditioning'), ('cleaning', 'Cleaning'), ('electrical', 'Electrical'), ('gardening', 'Gardening'), ('general_merchandise', 'General Merchandise'), ('glazing', 'Glazing'), ('pest_control', 'Pest Control'), ('plumbing-gas', 'Plumbing / Gas'), ('tree_cutting', 'Tree Cutting'), ('steel_works', 'Steel Works')], max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('municipality', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('address_line_1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
