# Generated by Django 4.2.11 on 2025-07-19 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgentRegister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=50)),
                ("contact_person", models.CharField(max_length=50)),
                ("agency_id", models.CharField(max_length=50)),
                ("website", models.CharField(max_length=50)),
                ("notes", models.CharField(blank=True, max_length=255, null=True)),
                ("password", models.CharField(max_length=255, null=True)),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "company_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "company_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "company_landline",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("contractor_license", models.CharField(blank=True, max_length=100)),
                (
                    "service",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("air_conditioning", "Air Conditioning"),
                            ("cleaning", "Cleaning"),
                            ("electrical", "Electrical"),
                            ("gardening", "Gardening"),
                            ("general_merchandise", "General Merchandise"),
                            ("glazing", "Glazing"),
                            ("pest_control", "Pest Control"),
                            ("plumbing-gas", "Plumbing / Gas"),
                            ("tree_cutting", "Tree Cutting"),
                            ("steel_works", "Steel Works"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("state", models.CharField(blank=True, max_length=100)),
                ("municipality", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                (
                    "address_line_1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_line_2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("postal_code", models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("floor_count", models.PositiveIntegerField(blank=True, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "renter_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "renter_contact",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "rent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "property_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="property_photos/"
                    ),
                ),
                (
                    "condition_report",
                    models.ImageField(
                        blank=True, null=True, upload_to="condition_reports/"
                    ),
                ),
                ("lease_start", models.DateField()),
                ("lease_end", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("occupied", "Occupied"), ("vacant", "Vacant")],
                        default="vacant",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rooms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_rooms",
                        to="agent.property",
                    ),
                ),
            ],
        ),
    ]
