# Generated by Django 5.2.1 on 2025-06-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('renter_name', models.CharField(max_length=100)),
                ('renter_contact', models.CharField(max_length=20)),
                ('lease_start', models.DateField()),
                ('lease_end', models.DateField()),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('occupied', 'Occupied'), ('vacant', 'Vacant')], default='vacant', max_length=10)),
            ],
        ),
    ]
