# Generated by Django 5.2.1 on 2025-06-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_property_agent_property_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='floor_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
