# Generated by Django 5.2.3 on 2025-08-04 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_property_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
