# Generated by Django 5.2.1 on 2025-08-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_alter_property_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentregister',
            name='service',
            field=models.CharField(blank=True, choices=[('air_conditioning', 'Air Conditioning'), ('cleaning', 'Cleaning'), ('electrical', 'Electrical'), ('gardening', 'Gardening'), ('general_maintenance', 'General Maintenance'), ('glazing', 'Glazing'), ('pest_control', 'Pest Control'), ('plumbing-gas', 'Plumbing / Gas'), ('tree_cutting', 'Tree Cutting'), ('steel_works', 'Steel Works')], max_length=100, null=True),
        ),
    ]
