# Generated by Django 4.2.11 on 2025-07-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0005_alter_property_agent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentregister",
            name="notes",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
