# Generated by Django 5.2.1 on 2025-08-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_alter_agentregister_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='house_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
