# Generated by Django 5.2.1 on 2025-08-25 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0006_property_house_number_property_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='ref_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
