# Generated by Django 5.2.1 on 2025-08-25 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0007_property_ref_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='key_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
