# Generated by Django 5.2.3 on 2025-11-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0010_lognote'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='room_photo',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/'),
        ),
    ]
