# Generated by Django 4.2.11 on 2025-06-04 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Renter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=128)),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "contact_person",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "contact_person_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("zip_code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "company_address_line1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "company_address_line2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "company_postal_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "upload_option",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "property_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="property_images/"
                    ),
                ),
                ("floor_count", models.PositiveIntegerField(blank=True, null=True)),
                ("room_count", models.PositiveIntegerField(blank=True, null=True)),
                ("rooms", models.JSONField(blank=True, null=True)),
                (
                    "address_line1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_line2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "house_state",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("house_city", models.CharField(blank=True, max_length=100, null=True)),
                ("house_zip", models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
