# Generated by Django 4.2.11 on 2025-07-19 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("renter", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="renterroom",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="renter_rooms",
                to="renter.property",
            ),
        ),
    ]
