# Generated by Django 5.2.1 on 2025-06-05 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renter', '0002_renter_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renter',
            name='user',
        ),
    ]
