# Generated by Django 4.2.11 on 2025-07-19 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0002_initial"),
        ("renter", "0002_alter_renterroom_property"),
    ]

    operations = [
        migrations.AlterField(
            model_name="renterroom",
            name="property",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="agent.property",
            ),
        ),
        migrations.AlterField(
            model_name="renterroom",
            name="renter",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="renter.renter",
            ),
        ),
        migrations.AlterField(
            model_name="renterroom",
            name="room_name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
