# Generated by Django 4.2.11 on 2025-07-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("renter", "0003_alter_renterroom_property_alter_renterroom_renter_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="renterroomareacondition",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="area_condition_photos/"
            ),
        ),
        migrations.AddField(
            model_name="renterroomareacondition",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
    ]
