# Generated by Django 4.2.11 on 2025-07-19 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("renter", "0004_renterroomareacondition_photo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomApplianceReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("window_height", models.CharField(blank=True, max_length=50)),
                ("window_length", models.CharField(blank=True, max_length=50)),
                ("window_width", models.CharField(blank=True, max_length=50)),
                ("brand", models.CharField(blank=True, max_length=100)),
                ("model_serial", models.CharField(blank=True, max_length=100)),
                ("location", models.CharField(blank=True, max_length=100)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="appliance_photos/"
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                (
                    "appliance_photo",
                    models.ImageField(blank=True, null=True, upload_to="appliances/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "renter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="renter.renter"
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appliances",
                        to="renter.renterroom",
                    ),
                ),
            ],
        ),
    ]
