# Generated by Django 5.2.1 on 2025-06-08 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renter', '0005_failedloginattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='failedloginattempt',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
