# Generated by Django 4.2.11 on 2025-07-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("renter", "0005_roomappliancereport"),
    ]

    operations = [
        migrations.AddField(
            model_name="renterroom",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="room_photos/"),
        ),
    ]
