# Generated by Django 4.2.11 on 2025-06-14 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("renter", "0006_failedloginattempt_locked_until"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConditionReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField()),
                (
                    "renter",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="renter.renter"
                    ),
                ),
            ],
        ),
    ]
