# Generated by Django 4.2.11 on 2025-07-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("renter", "0006_renterroom_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="minimumstandardreport",
            name="audit_expiry",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="minimumstandardreport",
            name="company",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="minimumstandardreport",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
