# Generated by Django 4.2.11 on 2025-07-25 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("renter", "0007_minimumstandardreport_audit_expiry_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MainConditionReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_number", models.CharField(max_length=100, unique=True)),
                ("date_created", models.DateField(auto_now_add=True)),
                (
                    "renter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="renter.renter"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConditionReportRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_rooms",
                        to="renter.mainconditionreport",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="renter.renterroom",
                    ),
                ),
            ],
        ),
    ]
