# Generated by Django 4.2.11 on 2025-07-26 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("renter", "0008_mainconditionreport_conditionreportroom"),
    ]

    operations = [
        migrations.AddField(
            model_name="mainconditionreport",
            name="uploaded_file",
            field=models.FileField(
                blank=True, null=True, upload_to="condition_reports/"
            ),
        ),
    ]
