# Generated by Django 4.2.11 on 2025-07-07 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("renter", "0009_alter_property_agent_alter_property_renter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="agent",
        ),
        migrations.AddField(
            model_name="renter",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="renter",
            name="gender",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="condition_report",
            field=models.FileField(
                blank=True, null=True, upload_to="condition_reports/"
            ),
        ),
        migrations.CreateModel(
            name="RoomCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_name", models.CharField(max_length=255)),
                ("width", models.CharField(blank=True, max_length=50, null=True)),
                ("length", models.CharField(blank=True, max_length=50, null=True)),
                ("photo", models.ImageField(blank=True, null=True, upload_to="rooms/")),
                ("condition_report_date", models.CharField(blank=True, max_length=100)),
                ("agreement_start_date", models.CharField(blank=True, max_length=100)),
                ("renter_received_date", models.CharField(blank=True, max_length=100)),
                ("report_return_date", models.CharField(blank=True, max_length=100)),
                ("address", models.TextField(blank=True)),
                ("full_name_1", models.CharField(blank=True, max_length=100)),
                ("agent_name", models.CharField(blank=True, max_length=100)),
                ("agent_company_name", models.CharField(blank=True, max_length=100)),
                ("renter_1", models.CharField(blank=True, max_length=100)),
                ("renter_2", models.CharField(blank=True, max_length=100)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="renter.property",
                    ),
                ),
                (
                    "renter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="renter.renter"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoomAreaCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area_name", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=100)),
                ("renter_comment", models.TextField(blank=True)),
                (
                    "room_condition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="areas",
                        to="renter.roomcondition",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MinimumStandardReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_name", models.CharField(max_length=255)),
                ("audit_no", models.CharField(max_length=100)),
                ("auditor", models.CharField(max_length=255)),
                ("inspection_address", models.TextField()),
                ("managing_agent", models.CharField(max_length=255)),
                ("audit_date", models.DateField()),
                ("room", models.CharField(max_length=255)),
                ("comments", models.TextField(blank=True, null=True)),
                (
                    "report_file",
                    models.FileField(
                        blank=True, null=True, upload_to="standard_reports/"
                    ),
                ),
                (
                    "renter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="renter.renter"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ApplianceReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("window_height", models.CharField(blank=True, max_length=50)),
                ("window_length", models.CharField(blank=True, max_length=50)),
                ("window_width", models.CharField(blank=True, max_length=50)),
                ("brand", models.CharField(blank=True, max_length=100)),
                ("model_serial", models.CharField(blank=True, max_length=100)),
                ("location", models.CharField(blank=True, max_length=100)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="appliance_photos/"
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "appliance_photo",
                    models.ImageField(blank=True, null=True, upload_to="appliances/"),
                ),
                (
                    "renter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="renter.renter"
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appliance_reports",
                        to="renter.room",
                    ),
                ),
            ],
        ),
    ]
