# Generated by Django 4.2.11 on 2025-08-10 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("renter", "0009_mainconditionreport_uploaded_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomappliancereport",
            name="photo1",
            field=models.ImageField(
                blank=True, null=True, upload_to="appliance_photos/"
            ),
        ),
        migrations.AddField(
            model_name="roomappliancereport",
            name="photo2",
            field=models.ImageField(
                blank=True, null=True, upload_to="appliance_photos/"
            ),
        ),
        migrations.AddField(
            model_name="roomappliancereport",
            name="photo3",
            field=models.ImageField(
                blank=True, null=True, upload_to="appliance_photos/"
            ),
        ),
        migrations.AddField(
            model_name="roomappliancereport",
            name="photo4",
            field=models.ImageField(
                blank=True, null=True, upload_to="appliance_photos/"
            ),
        ),
        migrations.AddField(
            model_name="roomappliancereport",
            name="photo5",
            field=models.ImageField(
                blank=True, null=True, upload_to="appliance_photos/"
            ),
        ),
    ]
