# Generated by Django 4.2.11 on 2025-08-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("renter", "0010_roomappliancereport_photo1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="renterroom",
            name="room_photo1",
            field=models.ImageField(blank=True, null=True, upload_to="room_photos/"),
        ),
        migrations.AddField(
            model_name="renterroom",
            name="room_photo2",
            field=models.ImageField(blank=True, null=True, upload_to="room_photos/"),
        ),
        migrations.AddField(
            model_name="renterroom",
            name="room_photo3",
            field=models.ImageField(blank=True, null=True, upload_to="room_photos/"),
        ),
        migrations.AddField(
            model_name="renterroom",
            name="room_photo4",
            field=models.ImageField(blank=True, null=True, upload_to="room_photos/"),
        ),
        migrations.AddField(
            model_name="renterroom",
            name="room_photo5",
            field=models.ImageField(blank=True, null=True, upload_to="room_photos/"),
        ),
    ]
