# Generated by Django 4.2.11 on 2025-08-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("renter", "0011_renterroom_room_photo1_renterroom_room_photo2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="renterroomareacondition",
            name="area_photo1",
            field=models.ImageField(
                blank=True, null=True, upload_to="area_condition_photos/"
            ),
        ),
        migrations.AddField(
            model_name="renterroomareacondition",
            name="area_photo2",
            field=models.ImageField(
                blank=True, null=True, upload_to="area_condition_photos/"
            ),
        ),
        migrations.AddField(
            model_name="renterroomareacondition",
            name="area_photo3",
            field=models.ImageField(
                blank=True, null=True, upload_to="area_condition_photos/"
            ),
        ),
        migrations.AddField(
            model_name="renterroomareacondition",
            name="area_photo4",
            field=models.ImageField(
                blank=True, null=True, upload_to="area_condition_photos/"
            ),
        ),
        migrations.AddField(
            model_name="renterroomareacondition",
            name="area_photo5",
            field=models.ImageField(
                blank=True, null=True, upload_to="area_condition_photos/"
            ),
        ),
    ]
