# Generated by Django 5.2.1 on 2025-09-23 11:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0008_property_key_number_property_property_id'),
        ('renter', '0012_renterroomareacondition_area_photo1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start', models.DateField()),
                ('end', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('maintenance', 'Maintenance Request Report'), ('condition', 'Condition Report'), ('appliance', 'Appliance Report'), ('minimum_standard', 'Minimum Standard Reports')], max_length=50, verbose_name='Type of Report')),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('date_requested', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='sent', max_length=20, verbose_name='Status')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_reports', to='agent.agentregister')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_reports', to='renter.renter')),
            ],
        ),
    ]
