# Generated by Django 4.2.11 on 2025-11-02 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("renter", "0013_event_requestreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="renter",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
    ]
