# Generated by Django 4.2.11 on 2025-09-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("renter", "0013_requestreport"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("start", models.DateField()),
                ("end", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
